### ISSUE TITLE
死循环

### ISSUE THREAD

**Issue by guakeliao** [Elors/LunarCore-Swift#3]
private func toString(_ num: Int?) -> [AnyObject?] {
        var arr = [AnyObject?]()
        var tempNum = num
        while tempNum != nil {
            arr.append(String(tempNum! & 1) as AnyObject?)
            tempNum = tempNum! >> 1
        }
        return arr.reversed()
    }
这个方法会死循环

**Comment by guakeliao** [comment]
循环判断条件应该是: tempNum != 0 吧

**Comment by Elors** [comment]
因为时间关系，这个项目暂时还没有完成，会有非常多的问题。因此可能没有什么学习价值。不过这个问题我刚刚已经修复了。
感谢你的问题和修正。
